In [ ]:
!pip install nltk
!pip install --upgrade sympy
!pip install --upgrade transformers
!pip install stanza
import nltk
from nltk.stem import WordNetLemmatizer#Lemmatization
from nltk.tokenize import word_tokenize #Lemmatization
import string
from sklearn.feature_extraction.text import TfidfVectorizer#TF-IDF
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup
import re  #regular expression
import stanza
from concurrent.futures import ThreadPoolExecutor
import ast
from nltk.corpus.reader.wordnet import NOUN, VERB, ADJ, ADV

Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from nltk) (4.67.1)
Requirement already satisfied: sympy in /usr/local/lib/python3.11/dist-packages (1.13.1)
Collecting sympy
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy) (1.3.0)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Installing collected packages: sympy
  Attempting uninstall: sympy
    Found existing installation: sympy 1.13.1
    Uninstalling sympy-1.13.1:
      Successfully uninstalled sympy-1.13.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.6.0+cu124 requires sympy==1.13.1; python_version >= "3.9", but you have sympy 1.14.0 which is incompatible.
Successfully installed sympy-1.14.0
Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.53.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.33.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (2025.3.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (4.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (1.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.6.15)
Requirement already satisfied: stanza in /usr/local/lib/python3.11/dist-packages (1.10.1)
Requirement already satisfied: emoji in /usr/local/lib/python3.11/dist-packages (from stanza) (2.14.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from stanza) (2.0.2)
Requirement already satisfied: protobuf>=3.15.0 in /usr/local/lib/python3.11/dist-packages (from stanza) (5.29.5)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from stanza) (2.32.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from stanza) (3.5)
Requirement already satisfied: torch>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from stanza) (2.6.0+cu124)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from stanza) (4.67.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=1.3.0->stanza) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.3.0->stanza) (4.14.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.3.0->stanza) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=1.3.0->stanza) (2025.3.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.3.0->stanza) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.3.0->stanza) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.3.0->stanza) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=1.3.0->stanza) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=1.3.0->stanza) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=1.3.0->stanza) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=1.3.0->stanza) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=1.3.0->stanza) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=1.3.0->stanza) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.3.0->stanza) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.3.0->stanza) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.3.0->stanza) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.3.0->stanza) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.3.0->stanza) (3.2.0)
Collecting sympy==1.13.1 (from torch>=1.3.0->stanza)
  Using cached sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.3.0->stanza) (1.3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->stanza) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->stanza) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->stanza) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->stanza) (2025.6.15)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.3.0->stanza) (3.0.2)
Using cached sympy-1.13.1-py3-none-any.whl (6.2 MB)
Installing collected packages: sympy
  Attempting uninstall: sympy
    Found existing installation: sympy 1.14.0
    Uninstalling sympy-1.14.0:
      Successfully uninstalled sympy-1.14.0
Successfully installed sympy-1.13.1

In [ ]:
nltk.download("wordnet")
nltk.download("omw-1.4")
nltk.download('punkt_tab')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
def other_cards(soup):
  Name = soup.find("p", class_="card-text-title").text.strip()
  type_card_element = soup.find("p", class_="card-text-type")
  effect= soup.find("div", class_="card-text")
  #Extract text from each element in all_examples
  all_examples_text = [example.text for example in effect]
  #Split the extracted text into lines
  lines = []
  for text in all_examples_text:
      lines.extend(text.splitlines())
  lines = [line for line in lines if line.strip() != '']
  Effect = lines[3] if len(lines) > 3 else None

  #Check if the element exists before accessing its text
  if type_card_element:
      type_card = type_card_element.text.strip()
      type_card = type_card.split("-")
      Type = type_card[0].strip()
  HP=None
  Name_Attack=None
  Attack=None
  Energy1=None
  Energy2=None
  Energy3=None
  Energy4=None
  Weakness=None
  Resistance=None
  Retreat=None
  return Name,Type,HP,Name_Attack,Attack,Effect,Energy1,Energy2,Energy3,Energy4,Weakness,Resistance, Retreat

In [ ]:
def divide_line(line):
  #Divide the texts in separate lines
  lines = line.split(" ")
  #Remove empty rows
  lines = [lines.strip() for lines in lines if lines.strip()]
  return lines[1]

In [ ]:
def data_update(url):

  #Request to the page
  response = requests.get(url)

  if response.status_code == 200:
      #Analysis of page content
      soup = BeautifulSoup(response.text, 'html.parser')

      type_card_element = soup.find("p", class_="card-text-type")

      #Check if the element exists before accessing its text
      if type_card_element:
          type_card = type_card_element.text.strip()
          type_card = type_card.split("-")
          card_type = type_card[0].strip()
      if card_type == "Pokémon":

        #Informations extraction
        Name = soup.find("span", class_="card-text-name").text.strip()

        card_info_text = soup.find("p", class_="card-text-title").text.strip()

        card_info_parts = card_info_text.split("-")
        Type = card_info_parts[1].strip()
        HP = card_info_parts[2].strip()
        Energy=" "
        Attack=" "

        all_examples = soup.find_all("p", class_="card-text-attack-info")

        all_examples_text = [example.text for example in all_examples]

        lines = []
        for text in all_examples_text:
            lines.extend(text.splitlines())

        lines = [line.strip() for line in lines if line.strip()]

        lines_with_numbers = [line for line in lines if re.search(r'\d', line)]

        span_element = soup.find("span", class_="ptcg-symbol").text.strip()

        if lines_with_numbers and span_element!="0":

            if len(lines) >= 3:
              if len(lines_with_numbers)>=2:
                Energy = lines[2]
                ln=lines_with_numbers[1]

                match = re.search(r'^(.*?)(\d+)([^\d]*)$', ln.strip())
                if match:
                    Name_Attack = match.group(1).strip()
                    Attack = match.group(2).strip()
                    Special_Char = match.group(3).strip()

              else:
                Energy = lines[0]
                ln=lines_with_numbers[0]

                match = re.search(r'^(.*?)(\d+)([^\d]*)$', ln.strip())
                if match:
                    Name_Attack = match.group(1).strip()
                    Attack = match.group(2).strip()
                    Special_Char = match.group(3).strip()


            elif len(lines) == 2:
                Energy = lines[0]
                line_attack = lines[1]
                match = re.search(r'^(.*?)(\d+)([^\d]*)$', line_attack.strip())

                if match:
                  Name_Attack = match.group(1).strip()
                  Attack = match.group(2).strip()

            Effect=None


        else:
            if len(lines) >= 3:
              Energy = lines[0]
              Name_Attack = lines[1]
              energy = lines[2]
              attack = lines[3]

            elif len(lines) == 2:
                Energy = lines[0]
                Name_Attack = lines[1]

            else:
                print("Less than two elements with the specified class found.")
            Effect=soup.find("p", class_="card-text-attack-effect").text.strip()
            Attack=None

        card_d = soup.find("p", class_="card-text-wrr").text.splitlines()

        lines2 = [card_d.strip() for card_d in card_d if card_d.strip()]

        if len(lines2) >= 3:
            l_Weakness = lines2[0]
            l_Resistance = lines2[1]
            l_Retreat = lines2[2]
        else:
            print("The text contains less than three useful lines.")

        Energy1 = Energy[0] if len(Energy) > 0 else None
        Energy2 = Energy[1] if len(Energy) > 1 else None
        Energy3 = Energy[2] if len(Energy) > 2 else None
        Energy4 = Energy[3] if len(Energy) > 3 else None

        Weakness=divide_line(l_Weakness)
        Resistance=divide_line(l_Resistance)
        Retreat=divide_line(l_Retreat)


      else:
        Name,Type,HP,Name_Attack,Attack,Effect,Energy1,Energy2,Energy3,Energy4,Weakness,Resistance, Retreat=other_cards(soup)

  else:
      print(f"ERROR REQUEST: {response.status_code}")

  return Name,Type,HP,Name_Attack,Attack,Effect,Energy1,Energy2,Energy3,Energy4,Weakness,Resistance, Retreat

In [ ]:

pokemon_data={
    "Trainer_Name":[],
    "Pokemon_Name":[],
    "Type":[],
    "HP":[],
    "Name_Attack":[],
    "Attack":[],
    "Effect":[],
    "Energy1":[],
    "Energy2":[],
    "Energy3":[],
    "Energy4":[],
    "Weakness":[],
    "Resistance":[],
    "Retreat":[],
    "N_cards":[]
}
pokemon=pd.DataFrame(pokemon_data)

In [ ]:
urltrainer = "https://limitlesstcg.com/tournaments/476"
#Make a request to the deck page
response = requests.get(urltrainer)

if response.status_code == 200:

    soup = BeautifulSoup(response.text, 'html.parser')
    table = soup.find("table", class_="data-table striped")

    if table:
        rows = table.find_all("tr")
        for row in rows:
            Trainer=row.get("data-name")
            link_tags = row.find_all("a")

            if len(link_tags) > 1:
                deck_link = link_tags[1]["href"]

                if "deck" in deck_link:
                    full_url = f"https://limitlesstcg.com{deck_link}"
                    deck_response = requests.get(full_url)

                    if deck_response.status_code == 200:
                        deck_soup = BeautifulSoup(deck_response.text, 'html.parser')
                        core_cards = deck_soup.find_all("div", class_="core-card")

                        for card in core_cards:
                            card_link = card.find("a")["href"]
                            full_card_url = f"https://limitlesstcg.com{card_link}"
                            Name,Type,HP,Name_Attack,Attack,Effect,Energy1,Energy2,Energy3,Energy4,Weakness,Resistance, Retreat=data_update(full_card_url)
                            quantity_element = card.find("span", class_="share")

                            if quantity_element:
                                quantity = quantity_element.text.strip()
                                N_cards = quantity[0].strip()

                            else:
                                N_cards = None
                                print("Quantity element not found.")

                            pokemon.loc[len(pokemon)]=[Trainer, Name,Type,HP,Name_Attack,Attack,Effect,Energy1,Energy2,Energy3,Energy4,Weakness,Resistance, Retreat, N_cards]

    else:
        print("Table not found on page.")
else:
    print(f"ERROR REQUEST: {response.status_code}")

POKEMON DATASET CREATED FOR DAVIDE MIGGIANO

In [ ]:

pokemon_davide={
    "Pokemon_Name":[],
    "Type":[],
    "HP":[],
    "Name_Attack":[],
    "Attack":[],
    "Effect":[],
    "Energy1":[],
    "Energy2":[],
    "Energy3":[],
    "Energy4":[],
    "Weakness":[],
    "Resistance":[],
    "Retreat":[],
    "N_cards": []
}
pokemondav=pd.DataFrame(pokemon_davide)
full_url = f"https://limitlesstcg.com/cards/N3"
#Make a request to the deck page
deck_responsee = requests.get(full_url)
if deck_responsee.status_code == 200:
    deck_soup = BeautifulSoup(deck_responsee.text, 'html.parser')

    core_cardss_container = deck_soup.find("div", class_="card-search-grid")
    core_cardss = core_cardss_container.find_all("a")
    print(len(core_cardss))
    for card in core_cardss:
        card_link = card["href"]
        print(card_link)
        full_card_urll = f"https://limitlesstcg.com{card_link}"

        Name,Type,HP,Name_Attack,Attack,Effect,Energy1,Energy2,Energy3,Energy4,Weakness,Resistance, Retreat=data_update(full_card_urll)
        #Card qyuantity extraction (how many cards are of that same type)
        quantity_element = card.find("span", class_="share")
        if quantity_element:
            quantity = quantity_element.text.strip()
            N_cards = quantity[0].strip()

        else:
            N_cards = None
            print("Quantity element not found.")
        pokemondav.loc[len(pokemondav)]=[Name,Type,HP,Name_Attack,Attack,Effect,Energy1,Energy2,Energy3,Energy4,Weakness,Resistance, Retreat, N_cards]

66
/cards/N3/1
Quantity element not found.
/cards/N3/2
Quantity element not found.
/cards/N3/3
Quantity element not found.
/cards/N3/4
Quantity element not found.
/cards/N3/5
Quantity element not found.
/cards/N3/6
Quantity element not found.
/cards/N3/7
Quantity element not found.
/cards/N3/8
Quantity element not found.
/cards/N3/9
Quantity element not found.
/cards/N3/10
Quantity element not found.
/cards/N3/11
Quantity element not found.
/cards/N3/12
Quantity element not found.
/cards/N3/13
Quantity element not found.
/cards/N3/14
Quantity element not found.
/cards/N3/15
Quantity element not found.
/cards/N3/16
Quantity element not found.
/cards/N3/17
Quantity element not found.
/cards/N3/18
Quantity element not found.
/cards/N3/19
Quantity element not found.
/cards/N3/20
Quantity element not found.
/cards/N3/21
Quantity element not found.
/cards/N3/22
Quantity element not found.
/cards/N3/23
Quantity element not found.
/cards/N3/24
Quantity element not found.
/cards/N3/25
Quantity element not found.
/cards/N3/26
Quantity element not found.
/cards/N3/27
Quantity element not found.
/cards/N3/28
Quantity element not found.
/cards/N3/29
Quantity element not found.
/cards/N3/30
Quantity element not found.
/cards/N3/31
Quantity element not found.
/cards/N3/32
Quantity element not found.
/cards/N3/33
Quantity element not found.
/cards/N3/34
Quantity element not found.
/cards/N3/35
Quantity element not found.
/cards/N3/36
Quantity element not found.
/cards/N3/37
Quantity element not found.
/cards/N3/38
Quantity element not found.
/cards/N3/39
Quantity element not found.
/cards/N3/40
Quantity element not found.
/cards/N3/41
Quantity element not found.
/cards/N3/42
Quantity element not found.
/cards/N3/43
Quantity element not found.
/cards/N3/44
Quantity element not found.
/cards/N3/45
Quantity element not found.
/cards/N3/46
Quantity element not found.
/cards/N3/47
Quantity element not found.
/cards/N3/48
Quantity element not found.
/cards/N3/49
Quantity element not found.
/cards/N3/50
Quantity element not found.
/cards/N3/51
Quantity element not found.
/cards/N3/52
Quantity element not found.
/cards/N3/53
Quantity element not found.
/cards/N3/54
Quantity element not found.
/cards/N3/55
Quantity element not found.
/cards/N3/56
Quantity element not found.
/cards/N3/57
Quantity element not found.
/cards/N3/58
Quantity element not found.
/cards/N3/59
Quantity element not found.
/cards/N3/60
Quantity element not found.
/cards/N3/61
Quantity element not found.
/cards/N3/62
Quantity element not found.
/cards/N3/63
Quantity element not found.
/cards/N3/64
Quantity element not found.
/cards/N3/65
Quantity element not found.
/cards/N3/66
Quantity element not found.

END POKEMON DATASET CREATED FOR DAVIDE MIGGIANO

In [ ]:
pokemon

,Trainer_Name,Pokemon_Name,Type,HP,Name_Attack,Attack,Effect,Energy1,Energy2,Energy3,Energy4,Weakness,Resistance,Retreat,N_cards
0,Keito Arai,Ralts,Psychic,70 HP,Psyshot,30,None,P,C,None,None,Darkness,Fighting,1,3
1,Keito Arai,Kirlia,Psychic,90 HP,Psychic,60,None,P,P,C,None,Darkness,Fighting,1,2
2,Keito Arai,Gardevoir ex,Psychic,310 HP,Miracle Force,190,None,P,P,C,None,Darkness,Fighting,2,2
3,Keito Arai,Munkidori,Psychic,110 HP,Mind Bend,60,None,P,C,None,None,Darkness,Fighting,1,3
4,Keito Arai,Scream Tail,Psychic,90 HP,Slap,30,None,P,None,None,None,Darkness,Fighting,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022,Raymond Siswara Wong,Nest Ball,Trainer,None,None,None,Search your deck for a Bas...,None,None,None,None,None,None,None,3
1023,Raymond Siswara Wong,Pal Pad,Trainer,None,None,None,Shuffle up to 2 Supporter ...,None,None,None,None,None,None,None,2
1024,Raymond Siswara Wong,Night Stretcher,Trainer,None,None,None,Put a Pokémon or a Basic E...,None,None,None,None,None,None,None,1
1025,Raymond Siswara Wong,Hisuian Heavy Ball,Trainer,None,None,None,Look at your face-down Pri...,None,None,None,None,None,None,None,1
1026,Raymond Siswara Wong,Handheld Fan,Trainer,None,None,None,If the Pokémon this card i...,None,None,None,None,None,None,None,1

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [ ]:
pokemon.to_csv('cele_pokemon.csv', index=False)

In [ ]:
pokemon_prova=pd.read_csv("cele_pokemon.csv")

In [ ]:
def clean_effect(text, word):
    if word in text:
        index = text.find(word)  #Find the location of the word
        end_index = text.find('.', index)  #Find the dot after the word
        if end_index != -1:
            return text[end_index + 1:].strip()  #Return the text after the dot
    return text  #Otherwise return original text

#Clean cards effects
pokemon_prova['Effect']=pokemon_prova['Effect'].fillna('').apply(lambda eff: clean_effect(eff, 'Prize'))
pokemon_prova['Effect']=pokemon_prova['Effect'].fillna('').apply(lambda eff: clean_effect(eff, 'If'))
pokemon_prova['Effect']=pokemon_prova['Effect'].fillna('').apply(lambda eff: clean_effect(eff, 'if'))

In [ ]:
pokemon_prova

,Trainer_Name,Pokemon_Name,Type,HP,Name_Attack,Attack,Effect,Energy1,Energy2,Energy3,Energy4,Weakness,Resistance,Retreat,N_cards
0,Keito Arai,Ralts,Psychic,70 HP,Psyshot,30.0,,P,C,NaN,NaN,Darkness,Fighting,1.0,3
1,Keito Arai,Kirlia,Psychic,90 HP,Psychic,60.0,,P,P,C,NaN,Darkness,Fighting,1.0,2
2,Keito Arai,Gardevoir ex,Psychic,310 HP,Miracle Force,190.0,,P,P,C,NaN,Darkness,Fighting,2.0,2
3,Keito Arai,Munkidori,Psychic,110 HP,Mind Bend,60.0,,P,C,NaN,NaN,Darkness,Fighting,1.0,3
4,Keito Arai,Scream Tail,Psychic,90 HP,Slap,30.0,,P,NaN,NaN,NaN,Darkness,Fighting,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022,Raymond Siswara Wong,Nest Ball,Trainer,NaN,NaN,NaN,Search your deck for a Bas...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
1023,Raymond Siswara Wong,Pal Pad,Trainer,NaN,NaN,NaN,Shuffle up to 2 Supporter ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
1024,Raymond Siswara Wong,Night Stretcher,Trainer,NaN,NaN,NaN,Put a Pokémon or a Basic E...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1025,Raymond Siswara Wong,Hisuian Heavy Ball,Trainer,NaN,NaN,NaN,") Then, shuffle your face-down Prize cards.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1026,Raymond Siswara Wong,Handheld Fan,Trainer,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [ ]:
def penn_to_wordnet(pos_tag):
    if pos_tag.startswith('N'):
        return NOUN
    elif pos_tag.startswith('V'):
        return VERB
    elif pos_tag.startswith('J'):
        return ADJ
    elif pos_tag.startswith('R'):
        return ADV
    else:
        return NOUN

In [ ]:
def lemmatization(text, pos_tags):
    wnl = WordNetLemmatizer()
    if not isinstance(text, str):
        return "", []
    #tokenization and lemmatization
    tokens = word_tokenize(text.translate(str.maketrans("","",string.punctuation)))
    wn_map = {w.lower(): penn_to_wordnet(tag) for w, tag in pos_tags}
    lemmatized_words = [
        wnl.lemmatize(tok, pos=wn_map.get(tok.lower(), NOUN))
        for tok in tokens
    ]
    lemmatized_text = " ".join(lemmatized_words)
    #reconstruct POS on lemmas
    lemmatized_pos_tags = [
        (wnl.lemmatize(word, pos=penn_to_wordnet(tag)).lower(), tag)
        for word, tag in pos_tags
    ]
    return lemmatized_text, lemmatized_pos_tags

In [ ]:

#Upload english language template
nlp_stanza = stanza.Pipeline('en', use_gpu=True)

#POS tagging with Stanza
def get_stanza_pos_tags(text):
    doc = nlp_stanza(text)
    pos_tags = []
    for sentence in doc.sentences:  #Access to sentences
        for word in sentence.words:  #Access to words
            pos_tags.append((word.text, word.xpos))
    return pos_tags

def process_batch(effects_batch):
    return [get_stanza_pos_tags(effect) for effect in effects_batch]

effects = pokemon_prova['Effect'].astype(str).tolist()

#Use ThreadPoolExecutor for parallel processing
with ThreadPoolExecutor() as executor:
    batch_size = 10  #Number of effects per parallel batch
    #Divide list of effects
    batches = [effects[i:i + batch_size] for i in range(0, len(effects), batch_size)]

    #POS tagging for each batch
    results = list(executor.map(process_batch, batches))

#Flattened result to obtain a list with POS
flattened_results = [item for sublist in results for item in sublist]

pokemon_prova['POS_Tags_stanza'] = pd.Series(flattened_results, index=pokemon_prova.index)

print(pokemon_prova[['Effect', 'POS_Tags_stanza']])

INFO:stanza:Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.10.0.json:   0%|  …

INFO:stanza:Downloaded file to /root/stanza_resources/resources.json
INFO:stanza:Loading these models for language: en (English):
============================================
| Processor    | Package                   |
--------------------------------------------
| tokenize     | combined                  |
| mwt          | combined                  |
| pos          | combined_charlm           |
| lemma        | combined_nocharlm         |
| constituency | ptb3-revised_charlm       |
| depparse     | combined_charlm           |
| sentiment    | sstplus_charlm            |
| ner          | ontonotes-ww-multi_charlm |
============================================

WARNING:stanza:GPU requested, but is not available!
INFO:stanza:Using device: cpu
INFO:stanza:Loading: tokenize
INFO:stanza:Loading: mwt
INFO:stanza:Loading: pos
INFO:stanza:Loading: lemma
INFO:stanza:Loading: constituency
INFO:stanza:Loading: depparse
INFO:stanza:Loading: sentiment
INFO:stanza:Loading: ner
INFO:stanza:Done loading processors!

                                                 Effect  \
0
1
2
3
4
...                                                 ...
1022                      Search your deck for a Bas...
1023                      Shuffle up to 2 Supporter ...
1024                      Put a Pokémon or a Basic E...
1025        ) Then, shuffle your face-down Prize cards.
1026

                                        POS_Tags_stanza
0                                                    []
1                                                    []
2                                                    []
3                                                    []
4                                                    []
...                                                 ...
1022  [(Search, VB), (your, PRP$), (deck, NN), (for,...
1023  [(Shuffle, VB), (up, IN), (to, IN), (2, CD), (...
1024  [(Put, VB), (a, DT), (Pokémon, NNP), (or, CC),...
1025  [(), -RRB-), (Then, RB), (,, ,), (shuffle, VB)...
1026                                                 []

[1027 rows x 2 columns]

In [ ]:
pokemon_prova['POS_Lemmatized'] = None
for idx, row in pokemon_prova.iterrows():
    if isinstance(row['Effect'], str):
        lem_text, lem_pos = lemmatization(row['Effect'], row['POS_Tags_stanza'])
        pokemon_prova.at[idx, 'Effect'] = lem_text
        pokemon_prova.at[idx, 'POS_Lemmatized'] = lem_pos

pokemon_prova

,Trainer_Name,Pokemon_Name,Type,HP,Name_Attack,Attack,Effect,Energy1,Energy2,Energy3,Energy4,Weakness,Resistance,Retreat,N_cards,POS_Tags_stanza,POS_Lemmatized
0,Keito Arai,Ralts,Psychic,70 HP,Psyshot,30.0,,P,C,NaN,NaN,Darkness,Fighting,1.0,3,[],[]
1,Keito Arai,Kirlia,Psychic,90 HP,Psychic,60.0,,P,P,C,NaN,Darkness,Fighting,1.0,2,[],[]
2,Keito Arai,Gardevoir ex,Psychic,310 HP,Miracle Force,190.0,,P,P,C,NaN,Darkness,Fighting,2.0,2,[],[]
3,Keito Arai,Munkidori,Psychic,110 HP,Mind Bend,60.0,,P,C,NaN,NaN,Darkness,Fighting,1.0,3,[],[]
4,Keito Arai,Scream Tail,Psychic,90 HP,Slap,30.0,,P,NaN,NaN,NaN,Darkness,Fighting,1.0,1,[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022,Raymond Siswara Wong,Nest Ball,Trainer,NaN,NaN,NaN,Search your deck for a Basic Pokémon and put i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,"[(Search, VB), (your, PRP$), (deck, NN), (for,...","[(search, VB), (your, PRP$), (deck, NN), (for,..."
1023,Raymond Siswara Wong,Pal Pad,Trainer,NaN,NaN,NaN,Shuffle up to 2 Supporter card from your disca...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,"[(Shuffle, VB), (up, IN), (to, IN), (2, CD), (...","[(shuffle, VB), (up, IN), (to, IN), (2, CD), (..."
1024,Raymond Siswara Wong,Night Stretcher,Trainer,NaN,NaN,NaN,Put a Pokémon or a Basic Energy card from your...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,"[(Put, VB), (a, DT), (Pokémon, NNP), (or, CC),...","[(put, VB), (a, DT), (pokémon, NNP), (or, CC),..."
1025,Raymond Siswara Wong,Hisuian Heavy Ball,Trainer,NaN,NaN,NaN,Then shuffle your facedown Prize card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,"[(), -RRB-), (Then, RB), (,, ,), (shuffle, VB)...","[(), -RRB-), (then, RB), (,, ,), (shuffle, VB)..."
1026,Raymond Siswara Wong,Handheld Fan,Trainer,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,[],[]

In [ ]:
#Calculation for “Num_Energy” considering
def calcola_num_energy(row):
    if row[["Energy1", "Energy2", "Energy3", "Energy4"]].isna().all():
        return np.nan
    if row["Energy1"] == '0':
        return 0
    return row[["Energy1", "Energy2", "Energy3", "Energy4"]].notna().sum()

pokemon_prova["Num_Energy"] = pokemon_prova.apply(calcola_num_energy, axis=1)

In [ ]:
pokemon_prova

,Trainer_Name,Pokemon_Name,Type,HP,Name_Attack,Attack,Effect,Energy1,Energy2,Energy3,Energy4,Weakness,Resistance,Retreat,N_cards,POS_Tags_stanza,POS_Lemmatized,Num_Energy
0,Keito Arai,Ralts,Psychic,70 HP,Psyshot,30.0,,P,C,NaN,NaN,Darkness,Fighting,1.0,3,[],[],2.0
1,Keito Arai,Kirlia,Psychic,90 HP,Psychic,60.0,,P,P,C,NaN,Darkness,Fighting,1.0,2,[],[],3.0
2,Keito Arai,Gardevoir ex,Psychic,310 HP,Miracle Force,190.0,,P,P,C,NaN,Darkness,Fighting,2.0,2,[],[],3.0
3,Keito Arai,Munkidori,Psychic,110 HP,Mind Bend,60.0,,P,C,NaN,NaN,Darkness,Fighting,1.0,3,[],[],2.0
4,Keito Arai,Scream Tail,Psychic,90 HP,Slap,30.0,,P,NaN,NaN,NaN,Darkness,Fighting,1.0,1,[],[],1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022,Raymond Siswara Wong,Nest Ball,Trainer,NaN,NaN,NaN,Search your deck for a Basic Pokémon and put i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,"[(Search, VB), (your, PRP$), (deck, NN), (for,...","[(search, VB), (your, PRP$), (deck, NN), (for,...",NaN
1023,Raymond Siswara Wong,Pal Pad,Trainer,NaN,NaN,NaN,Shuffle up to 2 Supporter card from your disca...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,"[(Shuffle, VB), (up, IN), (to, IN), (2, CD), (...","[(shuffle, VB), (up, IN), (to, IN), (2, CD), (...",NaN
1024,Raymond Siswara Wong,Night Stretcher,Trainer,NaN,NaN,NaN,Put a Pokémon or a Basic Energy card from your...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,"[(Put, VB), (a, DT), (Pokémon, NNP), (or, CC),...","[(put, VB), (a, DT), (pokémon, NNP), (or, CC),...",NaN
1025,Raymond Siswara Wong,Hisuian Heavy Ball,Trainer,NaN,NaN,NaN,Then shuffle your facedown Prize card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,"[(), -RRB-), (Then, RB), (,, ,), (shuffle, VB)...","[(), -RRB-), (then, RB), (,, ,), (shuffle, VB)...",NaN
1026,Raymond Siswara Wong,Handheld Fan,Trainer,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,[],[],NaN

In [ ]:
pokemon_prova["HP"] = pokemon_prova["HP"].str.extract(r"(\d+)")
pokemon_prova["HP"] = pokemon_prova["HP"].apply(lambda x: int(x.split()[0]) if isinstance(x, str) else None)

dare peso alle parole

In [ ]:
pokemon_prova

,Trainer_Name,Pokemon_Name,Type,HP,Name_Attack,Attack,Effect,Energy1,Energy2,Energy3,Energy4,Weakness,Resistance,Retreat,N_cards,POS_Tags_stanza,POS_Lemmatized,Num_Energy
0,Keito Arai,Ralts,Psychic,70.0,Psyshot,30.0,,P,C,NaN,NaN,Darkness,Fighting,1.0,3,[],[],2.0
1,Keito Arai,Kirlia,Psychic,90.0,Psychic,60.0,,P,P,C,NaN,Darkness,Fighting,1.0,2,[],[],3.0
2,Keito Arai,Gardevoir ex,Psychic,310.0,Miracle Force,190.0,,P,P,C,NaN,Darkness,Fighting,2.0,2,[],[],3.0
3,Keito Arai,Munkidori,Psychic,110.0,Mind Bend,60.0,,P,C,NaN,NaN,Darkness,Fighting,1.0,3,[],[],2.0
4,Keito Arai,Scream Tail,Psychic,90.0,Slap,30.0,,P,NaN,NaN,NaN,Darkness,Fighting,1.0,1,[],[],1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022,Raymond Siswara Wong,Nest Ball,Trainer,NaN,NaN,NaN,Search your deck for a Basic Pokémon and put i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,"[(Search, VB), (your, PRP$), (deck, NN), (for,...","[(search, VB), (your, PRP$), (deck, NN), (for,...",NaN
1023,Raymond Siswara Wong,Pal Pad,Trainer,NaN,NaN,NaN,Shuffle up to 2 Supporter card from your disca...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,"[(Shuffle, VB), (up, IN), (to, IN), (2, CD), (...","[(shuffle, VB), (up, IN), (to, IN), (2, CD), (...",NaN
1024,Raymond Siswara Wong,Night Stretcher,Trainer,NaN,NaN,NaN,Put a Pokémon or a Basic Energy card from your...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,"[(Put, VB), (a, DT), (Pokémon, NNP), (or, CC),...","[(put, VB), (a, DT), (pokémon, NNP), (or, CC),...",NaN
1025,Raymond Siswara Wong,Hisuian Heavy Ball,Trainer,NaN,NaN,NaN,Then shuffle your facedown Prize card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,"[(), -RRB-), (Then, RB), (,, ,), (shuffle, VB)...","[(), -RRB-), (then, RB), (,, ,), (shuffle, VB)...",NaN
1026,Raymond Siswara Wong,Handheld Fan,Trainer,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,[],[],NaN

In [ ]:
pokemon_prova

,Trainer_Name,Pokemon_Name,Type,HP,Name_Attack,Attack,Effect,Energy1,Energy2,Energy3,Energy4,Weakness,Resistance,Retreat,N_cards,POS_Tags_stanza,POS_Lemmatized,Num_Energy
0,Keito Arai,Ralts,Psychic,70.0,Psyshot,30.0,,P,C,NaN,NaN,Darkness,Fighting,1.0,3,[],[],2.0
1,Keito Arai,Kirlia,Psychic,90.0,Psychic,60.0,,P,P,C,NaN,Darkness,Fighting,1.0,2,[],[],3.0
2,Keito Arai,Gardevoir ex,Psychic,310.0,Miracle Force,190.0,,P,P,C,NaN,Darkness,Fighting,2.0,2,[],[],3.0
3,Keito Arai,Munkidori,Psychic,110.0,Mind Bend,60.0,,P,C,NaN,NaN,Darkness,Fighting,1.0,3,[],[],2.0
4,Keito Arai,Scream Tail,Psychic,90.0,Slap,30.0,,P,NaN,NaN,NaN,Darkness,Fighting,1.0,1,[],[],1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022,Raymond Siswara Wong,Nest Ball,Trainer,NaN,NaN,NaN,Search your deck for a Basic Pokémon and put i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,"[(Search, VB), (your, PRP$), (deck, NN), (for,...","[(search, VB), (your, PRP$), (deck, NN), (for,...",NaN
1023,Raymond Siswara Wong,Pal Pad,Trainer,NaN,NaN,NaN,Shuffle up to 2 Supporter card from your disca...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,"[(Shuffle, VB), (up, IN), (to, IN), (2, CD), (...","[(shuffle, VB), (up, IN), (to, IN), (2, CD), (...",NaN
1024,Raymond Siswara Wong,Night Stretcher,Trainer,NaN,NaN,NaN,Put a Pokémon or a Basic Energy card from your...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,"[(Put, VB), (a, DT), (Pokémon, NNP), (or, CC),...","[(put, VB), (a, DT), (pokémon, NNP), (or, CC),...",NaN
1025,Raymond Siswara Wong,Hisuian Heavy Ball,Trainer,NaN,NaN,NaN,Then shuffle your facedown Prize card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,"[(), -RRB-), (Then, RB), (,, ,), (shuffle, VB)...","[(), -RRB-), (then, RB), (,, ,), (shuffle, VB)...",NaN
1026,Raymond Siswara Wong,Handheld Fan,Trainer,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,[],[],NaN

In [ ]:
def fix_joined_words(text):
    text = re.sub(r'(\w)([A-Z])', r'\1 \2', text)  #Added a space between joined words
    return text
pokemon_prova['Effect']=pokemon_prova['Effect'].apply(fix_joined_words)

In [ ]:
pokemon_with_effect = pokemon_prova[pokemon_prova["Effect"].notna()]

#Effects for each trainer
trainer_effects = pokemon_with_effect.groupby("Trainer_Name")["Effect"].apply(lambda x: " ".join(x)).reset_index()

#Compute TF-IDF
vectorizer = TfidfVectorizer(stop_words="english")
X = vectorizer.fit_transform(trainer_effects["Effect"])

tfidf_df = pd.DataFrame(X.toarray(), index=trainer_effects["Trainer_Name"], columns=vectorizer.get_feature_names_out())

#Obtain 10 key words
def get_keywords(trainer):
    if trainer in tfidf_df.index:
        return tfidf_df.loc[trainer].nlargest(10).index.tolist()


def is_effect_present(effect):
    if pd.isna(effect):
        return False
    if isinstance(effect, str) and effect.strip() == "":
        return False
    if isinstance(effect, list) and len(effect) == 0:
        return False
    return True

pokemon_prova["KeyWord_Effect"] = pokemon_prova.apply(
    lambda row: get_keywords(row["Trainer_Name"]) if is_effect_present(row["Effect"]) else np.nan,
    axis=1
)

In [ ]:
pokemon_prova["HP"] = pd.to_numeric(pokemon_prova["HP"], errors="coerce")
pokemon_prova["Attack"] = pd.to_numeric(pokemon_prova["Attack"], errors="coerce")

In [ ]:
pokemon_prova.to_csv('pokemon_typecard.csv', index=False)

In [ ]:
pokemon_typecard=pd.read_csv("pokemon_typecard.csv")

In [ ]:
pokemon_typecard.to_csv('pokemon_typecard_post.csv', index=False)

In [ ]:
pokemon_typecard_post=pd.read_csv("pokemon_typecard_post.csv")

In [ ]:
pokemon_typecard_post

,Trainer_Name,Pokemon_Name,Type,HP,Name_Attack,Attack,Effect,Energy1,Energy2,Energy3,Energy4,Weakness,Resistance,Retreat,N_cards,POS_Tags_stanza,POS_Lemmatized,Num_Energy,KeyWord_Effect
0,Keito Arai,Ralts,Psychic,70.0,Psyshot,30.0,NaN,P,C,NaN,NaN,Darkness,Fighting,1.0,3,[],[],2.0,NaN
1,Keito Arai,Kirlia,Psychic,90.0,Psychic,60.0,NaN,P,P,C,NaN,Darkness,Fighting,1.0,2,[],[],3.0,NaN
2,Keito Arai,Gardevoir ex,Psychic,310.0,Miracle Force,190.0,NaN,P,P,C,NaN,Darkness,Fighting,2.0,2,[],[],3.0,NaN
3,Keito Arai,Munkidori,Psychic,110.0,Mind Bend,60.0,NaN,P,C,NaN,NaN,Darkness,Fighting,1.0,3,[],[],2.0,NaN
4,Keito Arai,Scream Tail,Psychic,90.0,Slap,30.0,NaN,P,NaN,NaN,NaN,Darkness,Fighting,1.0,1,[],[],1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022,Raymond Siswara Wong,Nest Ball,Trainer,NaN,NaN,NaN,Search your deck for a Basic Pokémon and put i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,"[('Search', 'VB'), ('your', 'PRP$'), ('deck', ...","[('search', 'VB'), ('your', 'PRP$'), ('deck', ...",NaN,"['card', 'deck', 'pokémon', 'number', 'opponen..."
1023,Raymond Siswara Wong,Pal Pad,Trainer,NaN,NaN,NaN,Shuffle up to 2 Supporter card from your disca...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,"[('Shuffle', 'VB'), ('up', 'IN'), ('to', 'IN')...","[('shuffle', 'VB'), ('up', 'IN'), ('to', 'IN')...",NaN,"['card', 'deck', 'pokémon', 'number', 'opponen..."
1024,Raymond Siswara Wong,Night Stretcher,Trainer,NaN,NaN,NaN,Put a Pokémon or a Basic Energy card from your...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,"[('Put', 'VB'), ('a', 'DT'), ('Pokémon', 'NNP'...","[('put', 'VB'), ('a', 'DT'), ('pokémon', 'NNP'...",NaN,"['card', 'deck', 'pokémon', 'number', 'opponen..."
1025,Raymond Siswara Wong,Hisuian Heavy Ball,Trainer,NaN,NaN,NaN,Then shuffle your facedown Prize card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,"[(')', '-RRB-'), ('Then', 'RB'), (',', ','), (...","[(')', '-RRB-'), ('then', 'RB'), (',', ','), (...",NaN,"['card', 'deck', 'pokémon', 'number', 'opponen..."
1026,Raymond Siswara Wong,Handheld Fan,Trainer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,[],[],NaN,NaN

In [ ]:
for index, value in pokemon_typecard['POS_Tags_stanza'].head(10).items():
    print('----')
    print(index)
    if isinstance(value, str):
      value = ast.literal_eval(value)
      for word, tag in value:
        if tag.startswith('VB'):
          print('VB', word)
        if tag.startswith('NN'):  #take VB, VBD, VBG, VBN, VBP, VBZ
          print('NN', word)
pokemon_typecard['POS_Tags_stanza'].head(10).items()

----
0
----
1
----
2
----
3
----
4
----
5
----
6
NN attack
VB does
NN damage
NN opponent
NN Pokémon
VB Do
VB apply
NN Weakness
NN Resistance
VB Benched
NN Pokémon
----
7
VB Discard
NN hand
VB draw
NN cards
----
8
----
9
VB Search
NN deck
NN Item
NN card
NN Pokémon
NN Tool
NN card
VB reveal
VB put
NN hand
VB shuffle
NN deck

In [ ]:
#Not null effects
effect_df = pokemon_typecard_post[pokemon_typecard_post['Effect'].notna()]
effect_df = effect_df.drop_duplicates(subset='Effect').copy()

effect_df['POS_Lemmatized'] = effect_df['POS_Lemmatized'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else [])

sample = effect_df
print(sample)
#Creation of semantic frames
def smart_extract(effect, pos_tags):
    verb = None
    verb2 = None
    subject = None
    who=None
    sub=None
    object_ = None
    target_ = None
    number = None

    #Find verb
    for i, (word, tag) in enumerate(pos_tags):
        print('Effetto', effect)
        wordwho= re.compile(rf"opponents", re.IGNORECASE)
        match = wordwho.search(effect)
        if match:
            who = match.group()
            sub = 'player'
        else:
            who = 'player'


        if tag in ("MD",):
            #Find negation
            if i + 1 < len(pos_tags) and pos_tags[i + 1][0].lower() in ("not", "nt"):
                if i + 2 < len(pos_tags) and pos_tags[i + 2][1].startswith("VB"):
                    verb = f"cant {pos_tags[i + 2][0].lower()}"
                    break
            elif i + 1 < len(pos_tags) and pos_tags[i + 1][1].startswith("VB"):
                verb = f"{word.lower()} {pos_tags[i + 1][0].lower()}"
                break
        elif tag.startswith("VB") and not verb:
            verb = word.lower()

    #Find first subj and obj
    nouns = [word for word, tag in pos_tags if tag in ("NN", "NNS", "NNP", "NNPS", "PRP", "VBN")]
    if nouns:
      if sub:
        subject = f'{sub} {nouns[0]}'
      else:
        subject = nouns[0]
    if len(nouns) > 1 :
      object_ = nouns[1]
      if nouns[1] == "damage":
        object_ = nouns[2]



    #Find number
    match_number = re.search(r'\b(\d+)\b', effect)
    if match_number:
        number = match_number.group(1)
    print('obj', object_)

    if object_:
        pattern1 = re.compile(rf"{object_}\s+card", re.IGNORECASE)
        match = pattern1.search(effect)
        if match:
            object_ = match.group()
        pattern2 = re.compile(rf"{object_}\s+Pokémon", re.IGNORECASE)
        print(pattern1, pattern2)
        match = pattern2.search(effect)
        if match:
            object_ = match.group()

    if verb == "switch":
      named_nouns = [word for word, tag in pos_tags if tag in ("NN", "NNS", "NNP", "NNPS", "VBN")]
      if len(named_nouns) >= 5:
          object_ = f"{named_nouns[1]} {named_nouns[2]}-{named_nouns[3]} {named_nouns[4]}"

    any_match = re.search(r'\bany\s+(\w+\s+\w+|\w+)', effect, re.IGNORECASE)
    if any_match:
        object_ = any_match.group(1)

    if verb == "discard" and subject and "hand" in subject.lower():
      verb += "+draw"

    if verb == "discard+draw" and number and object_=="card":
        object_ = f"{object_}({number})"
    elif verb == "do"  and "damage" in effect and number:
        verb = f"do_damage{number}"

    #If the word deck is present then a column must be added
    #with a second action indicating that you must shuffle the deck after the first action
    if subject == 'deck':
      verb2 = 'shuffle_deck'


    return verb, subject, who ,object_, verb2


sample[['azione', 'chi', 'a_chi',  'cosa', 'azione2']] = sample.apply(
    lambda row: pd.Series(smart_extract(row['Effect'], row['POS_Lemmatized'])),
    axis=1
)

sample[['Effect', 'azione', 'chi','a_chi', 'cosa', 'azione2']]

sample[['Effect']].to_csv('sample.csv', index=False)

           Trainer_Name                    Pokemon_Name      Type     HP  \
6            Keito Arai                  Fezandipiti ex  Darkness  210.0
7            Keito Arai            Professor's Research   Trainer    NaN
9            Keito Arai                           Arven   Trainer    NaN
10           Keito Arai                      Ultra Ball   Trainer    NaN
11           Keito Arai                  Earthen Vessel   Trainer    NaN
12           Keito Arai                       Nest Ball   Trainer    NaN
13           Keito Arai                      Rare Candy   Trainer    NaN
14           Keito Arai                 Night Stretcher   Trainer    NaN
15           Keito Arai                       Super Rod   Trainer    NaN
16           Keito Arai                 Counter Catcher   Trainer    NaN
17           Keito Arai                      Secret Box   Trainer    NaN
18           Keito Arai    Technical Machine: Evolution   Trainer    NaN
19           Keito Arai                   Bravery Charm   Trainer    NaN
20           Keito Arai                         Artazon   Trainer    NaN
24           Hiro Yaoka                           Budew     Grass   30.0
34           Hiro Yaoka                   Boss's Orders   Trainer    NaN
38           Hiro Yaoka              Colress's Tenacity   Trainer    NaN
42           Hiro Yaoka              Hisuian Heavy Ball   Trainer    NaN
44           Hiro Yaoka                Precious Trolley   Trainer    NaN
45           Hiro Yaoka  Ancient Booster Energy Capsule   Trainer    NaN
46           Hiro Yaoka                   Binding Mochi   Trainer    NaN
47           Hiro Yaoka               Forest Seal Stone   Trainer    NaN
48           Hiro Yaoka           Area Zero Underdepths   Trainer    NaN
49           Hiro Yaoka             Double Turbo Energy    Energy    NaN
84            Yuhao Xia                         Crispin   Trainer    NaN
87            Yuhao Xia                    Pokégear 3.0   Trainer    NaN
90            Yuhao Xia              Buddy-Buddy Poffin   Trainer    NaN
93            Yuhao Xia                     Lost Vacuum   Trainer    NaN
96            Yuhao Xia   Future Booster Energy Capsule   Trainer    NaN
103            Peter Lo                 Regidrago VSTAR    Dragon  280.0
107            Peter Lo                          Kyurem    Dragon  130.0
116            Peter Lo                   Energy Switch   Trainer    NaN
196       Jordan Palmer       Professor Turo's Scenario   Trainer    NaN
250        Jake Dunstan                           Penny   Trainer    NaN
251        Jake Dunstan                         Cyllene   Trainer    NaN
252        Jake Dunstan            Miss Fortune Sisters   Trainer    NaN
254        Jake Dunstan                             Eri   Trainer    NaN
256        Jake Dunstan               Team Yell's Cheer   Trainer    NaN
257        Jake Dunstan          Xerosic's Machinations   Trainer    NaN
259        Jake Dunstan              Accompanying Flute   Trainer    NaN
262        Jake Dunstan                         Pal Pad   Trainer    NaN
436        Kelvin Duong                Radiant Greninja     Water  130.0
439        Kelvin Duong             Explorer's Guidance   Trainer    NaN
446        Kelvin Duong       Superior Energy Retrieval   Trainer    NaN
483   Bjorn Soh Cai Wei                            Jacq   Trainer    NaN
485   Bjorn Soh Cai Wei                 Capturing Aroma   Trainer    NaN
487   Bjorn Soh Cai Wei                      Jet Energy    Energy    NaN
489   Bjorn Soh Cai Wei                     Mist Energy    Energy    NaN
491   Bjorn Soh Cai Wei                   Legacy Energy    Energy    NaN
509        Tim Franklin                   Glass Trumpet   Trainer    NaN
587       Angus Johnson            Colress's Experiment   Trainer    NaN
592       Angus Johnson                     Mirage Gate   Trainer    NaN
595       Angus Johnson                          Switch   Trainer    NaN
629   Devan Kyle Timbol                          Mew ex   Psychic  180.0
642   Devan Kyle Timbol                   Jamming Tower   Trainer    NaN
691  Aaron Van Der Kolk     Ciphermaniac's Codebreaking   Trainer    NaN
704  Aaron Van Der Kolk               Energy Search Pro   Trainer    NaN
786          Jeremy Lim                           Irida   Trainer    NaN
934          Justin Hoy              Electric Generator   Trainer    NaN

            Name_Attack  Attack  \
6           Cruel Arrow     NaN
7                   NaN     NaN
9                   NaN     NaN
10                  NaN     NaN
11                  NaN     NaN
12                  NaN     NaN
13                  NaN     NaN
14                  NaN     NaN
15                  NaN     NaN
16                  NaN     NaN
17                  NaN     NaN
18                  NaN     NaN
19                  NaN     NaN
20                  NaN     NaN
24      Itchy Pollen 10     NaN
34                  NaN     NaN
38                  NaN     NaN
42                  NaN     NaN
44                  NaN     NaN
45                  NaN     NaN
46                  NaN     NaN
47                  NaN     NaN
48                  NaN     NaN
49                  NaN     NaN
84                  NaN     NaN
87                  NaN     NaN
90                  NaN     NaN
93                  NaN     NaN
96                  NaN     NaN
103         Apex Dragon     NaN
107            Trifrost     NaN
116                 NaN     NaN
196                 NaN     NaN
250                 NaN     NaN
251                 NaN     NaN
252                 NaN     NaN
254                 NaN     NaN
256                 NaN     NaN
257                 NaN     NaN
259                 NaN     NaN
262                 NaN     NaN
436  Moonlight Shuriken     NaN
439                 NaN     NaN
446                 NaN     NaN
483                 NaN     NaN
485                 NaN     NaN
487                 NaN     NaN
489                 NaN     NaN
491                 NaN     NaN
509                 NaN     NaN
587                 NaN     NaN
592                 NaN     NaN
595                 NaN     NaN
629      Genome Hacking     NaN
642                 NaN     NaN
691                 NaN     NaN
704                 NaN     NaN
786                 NaN     NaN
934                 NaN     NaN

                                                Effect Energy1 Energy2  \
6    This attack do 100 damage to 1 of your opponen...       C       C
7                    Discard your hand and draw 7 card     NaN     NaN
9    Search your deck for an Item card and a Pokémo...     NaN     NaN
10   Search your deck for a Pokémon reveal it and p...     NaN     NaN
11   Search your deck for up to 2 Basic Energy card...     NaN     NaN
12   Search your deck for a Basic Pokémon and put i...     NaN     NaN
13   This count a evolve that Pokémon You cant use ...     NaN     NaN
14   Put a Pokémon or a Basic Energy card from your...     NaN     NaN
15   Shuffle up to 3 in any combination of Pokémon ...     NaN     NaN
16   Switch in 1 of your opponent Benched Pokémon t...     NaN     NaN
17   Search your deck for an Item card a Pokémon To...     NaN     NaN
18   C Evolution Choose up to 2 of your Benched Pok...     NaN     NaN
19   The Basic Pokémon this card be attach to get 5...     NaN     NaN
20   Once during each player turn that player may s...     NaN     NaN
24   During your opponent next turn they cant play ...       0     NaN
34   Switch 1 of your opponent Benched Pokémon with...     NaN     NaN
38   Search your deck for a Stadium card and an Ene...     NaN     NaN
42               Then shuffle your facedown Prize card     NaN     NaN
44   Search your deck for any number of Basic Pokém...     NaN     NaN
45   The Ancient Pokémon this card be attach to get...     NaN     NaN
46   Attacks use by the Poisoned Pokémon this card ...     NaN     NaN
47   The Pokémon V this card be attach to can use t...     NaN     NaN
48   When this card leave play both player discard ...     NaN     NaN
49   As long a this card be attach to a Pokémon it ...     NaN     NaN
84   Attach the other to 1 of your Pokémon Then shu...     NaN     NaN
87   Look at the top 7 card of your deck You may re...     NaN     NaN
90   Search your deck for up to 2 Basic Pokémon wit...     NaN     NaN
93   Choose a Pokémon Tool attach to any Pokémon or...     NaN     NaN
96   The Future Pokémon this card be attach to have...     NaN     NaN
103  Choose an attack from a N Pokémon in your disc...       G       G
107  Discard all Energy from this Pokémon This atta...       W       W
116  Move a basic Energy from 1 of your Pokémon to ...     NaN     NaN
196  Put 1 of your Pokémon in play into your hand D...     NaN     NaN
250  Put 1 of your Basic Pokémon and all attach car...     NaN     NaN
251  Flip 2 coin Put a number of card up to the num...     NaN     NaN
252  Look at the top 5 card of your opponent deck a...     NaN     NaN
254  Your opponent reveal their hand and you discar...     NaN     NaN
256  Shuffle up to 3 in any combination of Pokémon ...     NaN     NaN
257  Your opponent discard card from their hand unt...     NaN     NaN
259  Reveal the top 5 card of your opponent deck Yo...     NaN     NaN
262  Shuffle up to 2 Supporter card from your disca...     NaN     NaN
436  Discard 2 Energy from this Pokémon This attack...       W       W
439  Look at the top 6 card of your deck and put 2 ...     NaN     NaN
446  Put 4 basic Energy card from your discard pile...     NaN     NaN
483  Search your deck for up to 2 Evolution Pokémon...     NaN     NaN
485  If tail search your deck for a Basic Pokémon r...     NaN     NaN
487  As long a this card be attach to a Pokémon it ...     NaN     NaN
489  As long a this card be attach to a Pokémon it ...     NaN     NaN
491  This effect of your Legacy Energy cant be appl...     NaN     NaN
509  Choose up to 2 of your Benched C Pokémon and a...     NaN     NaN
587  Look at the top 5 card of your deck and put 3 ...     NaN     NaN
592  Search your deck for up to 2 basic Energy card...     NaN     NaN
595  Switch your Active Pokémon with 1 of your Benc...     NaN     NaN
629  Choose 1 of your opponent Active Pokémons atta...       C       C
642  Pokémon Tools attach to each Pokémon both your...     NaN     NaN
691  Search your deck for 2 card shuffle your deck ...     NaN     NaN
704                             Then shuffle your deck     NaN     NaN
786  Search your deck for a W Pokémon and an Item c...     NaN     NaN
934  Look at the top 5 card of your deck and attach...     NaN     NaN

    Energy3 Energy4   Weakness Resistance  Retreat  N_cards  \
6         C     NaN   Fighting       none      1.0        1
7       NaN     NaN        NaN        NaN      NaN        3
9       NaN     NaN        NaN        NaN      NaN        1
10      NaN     NaN        NaN        NaN      NaN        4
11      NaN     NaN        NaN        NaN      NaN        3
12      NaN     NaN        NaN        NaN      NaN        2
13      NaN     NaN        NaN        NaN      NaN        1
14      NaN     NaN        NaN        NaN      NaN        2
15      NaN     NaN        NaN        NaN      NaN        1
16      NaN     NaN        NaN        NaN      NaN        1
17      NaN     NaN        NaN        NaN      NaN        1
18      NaN     NaN        NaN        NaN      NaN        1
19      NaN     NaN        NaN        NaN      NaN        1
20      NaN     NaN        NaN        NaN      NaN        2
24      NaN     NaN       Fire       none      0.0        1
34      NaN     NaN        NaN        NaN      NaN        3
38      NaN     NaN        NaN        NaN      NaN        1
42      NaN     NaN        NaN        NaN      NaN        2
44      NaN     NaN        NaN        NaN      NaN        1
45      NaN     NaN        NaN        NaN      NaN        2
46      NaN     NaN        NaN        NaN      NaN        3
47      NaN     NaN        NaN        NaN      NaN        1
48      NaN     NaN        NaN        NaN      NaN        3
49      NaN     NaN        NaN        NaN      NaN        4
84      NaN     NaN        NaN        NaN      NaN        4
87      NaN     NaN        NaN        NaN      NaN        3
90      NaN     NaN        NaN        NaN      NaN        1
93      NaN     NaN        NaN        NaN      NaN        1
96      NaN     NaN        NaN        NaN      NaN        1
103       R     NaN       none       none      3.0        3
107       M       M       none       none      2.0        1
116     NaN     NaN        NaN        NaN      NaN        4
196     NaN     NaN        NaN        NaN      NaN        1
250     NaN     NaN        NaN        NaN      NaN        2
251     NaN     NaN        NaN        NaN      NaN        1
252     NaN     NaN        NaN        NaN      NaN        1
254     NaN     NaN        NaN        NaN      NaN        1
256     NaN     NaN        NaN        NaN      NaN        1
257     NaN     NaN        NaN        NaN      NaN        1
259     NaN     NaN        NaN        NaN      NaN        3
262     NaN     NaN        NaN        NaN      NaN        2
436       C     NaN  Lightning       none      1.0        1
439     NaN     NaN        NaN        NaN      NaN        4
446     NaN     NaN        NaN        NaN      NaN        1
483     NaN     NaN        NaN        NaN      NaN        1
485     NaN     NaN        NaN        NaN      NaN        4
487     NaN     NaN        NaN        NaN      NaN        4
489     NaN     NaN        NaN        NaN      NaN        2
491     NaN     NaN        NaN        NaN      NaN        1
509     NaN     NaN        NaN        NaN      NaN        1
587     NaN     NaN        NaN        NaN      NaN        4
592     NaN     NaN        NaN        NaN      NaN        4
595     NaN     NaN        NaN        NaN      NaN        2
629       C     NaN   Darkness   Fighting      0.0        1
642     NaN     NaN        NaN        NaN      NaN        1
691     NaN     NaN        NaN        NaN      NaN        2
704     NaN     NaN        NaN        NaN      NaN        1
786     NaN     NaN        NaN        NaN      NaN        1
934     NaN     NaN        NaN        NaN      NaN        4

                                       POS_Tags_stanza  \
6    [('This', 'DT'), ('attack', 'NN'), ('does', 'V...
7    [('Discard', 'VB'), ('your', 'PRP$'), ('hand',...
9    [('Search', 'VB'), ('your', 'PRP$'), ('deck', ...
10   [('Search', 'VB'), ('your', 'PRP$'), ('deck', ...
11   [('Search', 'VB'), ('your', 'PRP$'), ('deck', ...
12   [('Search', 'VB'), ('your', 'PRP$'), ('deck', ...
13   [('(', '-LRB-'), ('This', 'DT'), ('counts', 'V...
14   [('Put', 'VB'), ('a', 'DT'), ('Pokémon', 'NNP'...
15   [('Shuffle', 'VB'), ('up', 'IN'), ('to', 'IN')...
16   [('Switch', 'VB'), ('in', 'IN'), ('1', 'CD'), ...
17   [('Search', 'VB'), ('your', 'PRP$'), ('deck', ...
18   [('[', '-LRB-'), ('C', 'NNP'), (']', '-RRB-'),...
19   [('The', 'DT'), ('Basic', 'NNP'), ('Pokémon', ...
20   [('Once', 'IN'), ('during', 'IN'), ('each', 'D...
24   [('During', 'IN'), ('your', 'PRP$'), ('opponen...
34   [('Switch', 'VB'), ('1', 'CD'), ('of', 'IN'), ...
38   [('Search', 'VB'), ('your', 'PRP$'), ('deck', ...
42   [(')', '-RRB-'), ('Then', 'RB'), (',', ','), (...
44   [('Search', 'VB'), ('your', 'PRP$'), ('deck', ...
45   [('The', 'DT'), ('Ancient', 'NNP'), ('Pokémon'...
46   [('Attacks', 'NNS'), ('used', 'VBN'), ('by', '...
47   [('The', 'DT'), ('Pokémon', 'NNP'), ('V', 'CD'...
48   [('When', 'WRB'), ('this', 'DT'), ('card', 'NN...
49   [('As', 'RB'), ('long', 'RB'), ('as', 'IN'), (...
84   [('Attach', 'VB'), ('the', 'DT'), ('other', 'J...
87   [('Look', 'VB'), ('at', 'IN'), ('the', 'DT'), ...
90   [('Search', 'VB'), ('your', 'PRP$'), ('deck', ...
93   [('Choose', 'VB'), ('a', 'DT'), ('Pokémon', 'N...
96   [('The', 'DT'), ('Future', 'NNP'), ('Pokémon',...
103  [('Choose', 'VB'), ('an', 'DT'), ('attack', 'N...
107  [('Discard', 'VB'), ('all', 'DT'), ('Energy', ...
116  [('Move', 'VB'), ('a', 'DT'), ('basic', 'JJ'),...
196  [('Put', 'VB'), ('1', 'CD'), ('of', 'IN'), ('y...
250  [('Put', 'VB'), ('1', 'CD'), ('of', 'IN'), ('y...
251  [('Flip', 'VB'), ('2', 'CD'), ('coins', 'NNS')...
252  [('Look', 'VB'), ('at', 'IN'), ('the', 'DT'), ...
254  [('Your', 'PRP$'), ('opponent', 'NN'), ('revea...
256  [('Shuffle', 'VB'), ('up', 'IN'), ('to', 'IN')...
257  [('Your', 'PRP$'), ('opponent', 'NN'), ('disca...
259  [('Reveal', 'VB'), ('the', 'DT'), ('top', 'JJ'...
262  [('Shuffle', 'VB'), ('up', 'IN'), ('to', 'IN')...
436  [('Discard', 'VB'), ('2', 'CD'), ('Energy', 'N...
439  [('Look', 'VB'), ('at', 'IN'), ('the', 'DT'), ...
446  [(')', '-RRB-'), ('Put', 'VB'), ('4', 'CD'), (...
483  [('Search', 'VB'), ('your', 'PRP$'), ('deck', ...
485  [('If', 'IN'), ('tails', 'NNS'), (',', ','), (...
487  [('As', 'RB'), ('long', 'RB'), ('as', 'IN'), (...
489  [('As', 'RB'), ('long', 'RB'), ('as', 'IN'), (...
491  [('This', 'DT'), ('effect', 'NN'), ('of', 'IN'...
509  [('Choose', 'VB'), ('up', 'IN'), ('to', 'IN'),...
587  [('Look', 'VB'), ('at', 'IN'), ('the', 'DT'), ...
592  [('Search', 'VB'), ('your', 'PRP$'), ('deck', ...
595  [('Switch', 'VB'), ('your', 'PRP$'), ('Active'...
629  [('Choose', 'VB'), ('1', 'CD'), ('of', 'IN'), ...
642  [('Pokémon', 'NNP'), ('Tools', 'NNS'), ('attac...
691  [('Search', 'VB'), ('your', 'PRP$'), ('deck', ...
704  [('Then', 'RB'), (',', ','), ('shuffle', 'VB')...
786  [('Search', 'VB'), ('your', 'PRP$'), ('deck', ...
934  [('Look', 'VB'), ('at', 'IN'), ('the', 'DT'), ...

                                        POS_Lemmatized  Num_Energy  \
6    [(this, DT), (attack, NN), (do, VBZ), (100, CD...         3.0
7    [(discard, VB), (your, PRP$), (hand, NN), (and...         NaN
9    [(search, VB), (your, PRP$), (deck, NN), (for,...         NaN
10   [(search, VB), (your, PRP$), (deck, NN), (for,...         NaN
11   [(search, VB), (your, PRP$), (deck, NN), (for,...         NaN
12   [(search, VB), (your, PRP$), (deck, NN), (for,...         NaN
13   [((, -LRB-), (this, DT), (count, VBZ), (a, IN)...         NaN
14   [(put, VB), (a, DT), (pokémon, NNP), (or, CC),...         NaN
15   [(shuffle, VB), (up, IN), (to, IN), (3, CD), (...         NaN
16   [(switch, VB), (in, IN), (1, CD), (of, IN), (y...         NaN
17   [(search, VB), (your, PRP$), (deck, NN), (for,...         NaN
18   [([, -LRB-), (c, NNP), (], -RRB-), (evolutionc...         NaN
19   [(the, DT), (basic, NNP), (pokémon, NNP), (thi...         NaN
20   [(once, IN), (during, IN), (each, DT), (player...         NaN
24   [(during, IN), (your, PRP$), (opponent, NN), (...         0.0
34   [(switch, VB), (1, CD), (of, IN), (your, PRP$)...         NaN
38   [(search, VB), (your, PRP$), (deck, NN), (for,...         NaN
42   [(), -RRB-), (then, RB), (,, ,), (shuffle, VB)...         NaN
44   [(search, VB), (your, PRP$), (deck, NN), (for,...         NaN
45   [(the, DT), (ancient, NNP), (pokémon, NNP), (t...         NaN
46   [(attacks, NNS), (use, VBN), (by, IN), (the, D...         NaN
47   [(the, DT), (pokémon, NNP), (v, CD), (this, DT...         NaN
48   [(when, WRB), (this, DT), (card, NN), (leave, ...         NaN
49   [(as, RB), (long, RB), (a, IN), (this, DT), (c...         NaN
84   [(attach, VB), (the, DT), (other, JJ), (to, IN...         NaN
87   [(look, VB), (at, IN), (the, DT), (top, JJ), (...         NaN
90   [(search, VB), (your, PRP$), (deck, NN), (for,...         NaN
93   [(choose, VB), (a, DT), (pokémon, NNP), (tool,...         NaN
96   [(the, DT), (future, NNP), (pokémon, NNP), (th...         NaN
103  [(choose, VB), (an, DT), (attack, NN), (from, ...         3.0
107  [(discard, VB), (all, DT), (energy, NN), (from...         4.0
116  [(move, VB), (a, DT), (basic, JJ), (energy, NN...         NaN
196  [(put, VB), (1, CD), (of, IN), (your, PRP$), (...         NaN
250  [(put, VB), (1, CD), (of, IN), (your, PRP$), (...         NaN
251  [(flip, VB), (2, CD), (coin, NNS), (., .), (pu...         NaN
252  [(look, VB), (at, IN), (the, DT), (top, JJ), (...         NaN

In [ ]:
#Merge between dataset
toooo = pokemon_typecard.merge(
    sample[['Effect', 'azione', 'chi', 'a_chi', 'cosa', 'azione2']],
    on='Effect',
    how='left'
)

In [ ]:
toooo.to_csv("Pokeomn_vero.csv", index=False)

In [ ]:
#Change type of file to JASON
toooo.to_json("Pokemon.json", orient="records", force_ascii=False, indent=4)

In [ ]:

toooo.head(22)

,Trainer_Name,Pokemon_Name,Type,HP,Name_Attack,Attack,Effect,Energy1,Energy2,Energy3,Energy4,Weakness,Resistance,Retreat,N_cards,POS_Tags_stanza,POS_Lemmatized,Num_Energy,KeyWord_Effect,azione,chi,a_chi,cosa,azione2
0,Keito Arai,Ralts,Psychic,70.0,Psyshot,30.0,NaN,P,C,NaN,NaN,Darkness,Fighting,1.0,3,[],[],2.0,NaN,NaN,NaN,NaN,NaN,NaN
1,Keito Arai,Kirlia,Psychic,90.0,Psychic,60.0,NaN,P,P,C,NaN,Darkness,Fighting,1.0,2,[],[],3.0,NaN,NaN,NaN,NaN,NaN,NaN
2,Keito Arai,Gardevoir ex,Psychic,310.0,Miracle Force,190.0,NaN,P,P,C,NaN,Darkness,Fighting,2.0,2,[],[],3.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Keito Arai,Munkidori,Psychic,110.0,Mind Bend,60.0,NaN,P,C,NaN,NaN,Darkness,Fighting,1.0,3,[],[],2.0,NaN,NaN,NaN,NaN,NaN,NaN
4,Keito Arai,Scream Tail,Psychic,90.0,Slap,30.0,NaN,P,NaN,NaN,NaN,Darkness,Fighting,1.0,1,[],[],1.0,NaN,NaN,NaN,NaN,NaN,NaN
5,Keito Arai,Lillie's Clefairy ex,Psychic,190.0,Full Moon Rondo,20.0,NaN,P,C,NaN,NaN,Metal,none,1.0,1,[],[],2.0,NaN,NaN,NaN,NaN,NaN,NaN
6,Keito Arai,Fezandipiti ex,Darkness,210.0,Cruel Arrow,NaN,This attack do 100 damage to 1 of your opponent Pokémon Dont apply Weakness and Resistance for Benched Pokémon,C,C,C,NaN,Fighting,none,1.0,1,"[('This', 'DT'), ('attack', 'NN'), ('does', 'VBZ'), ('100', 'CD'), ('damage', 'NN'), ('to', 'IN'), ('1', 'CD'), ('of', 'IN'), ('your', 'PRP$'), ('opponent', 'NN'), (""'s"", 'POS'), ('Pokémon', 'NNP'), ('.', '.'), ('(', '-LRB-'), ('Do', 'VB'), (""n't"", 'RB'), ('apply', 'VB'), ('Weakness', 'NN'), ('and', 'CC'), ('Resistance', 'NN'), ('for', 'IN'), ('Benched', 'VBN'), ('Pokémon', 'NNP'), ('.', '.'), (')', '-RRB-')]","[('this', 'DT'), ('attack', 'NN'), ('do', 'VBZ'), ('100', 'CD'), ('damage', 'NN'), ('to', 'IN'), ('1', 'CD'), ('of', 'IN'), ('your', 'PRP$'), ('opponent', 'NN'), (""'s"", 'POS'), ('pokémon', 'NNP'), ('.', '.'), ('(', '-LRB-'), ('do', 'VB'), (""n't"", 'RB'), ('apply', 'VB'), ('weakness', 'NN'), ('and', 'CC'), ('resistance', 'NN'), ('for', 'IN'), ('benched', 'VBN'), ('pokémon', 'NNP'), ('.', '.'), (')', '-RRB-')]",3.0,"['pokémon', 'deck', 'card', 'shuffle', 'basic', 'search', 'hand', 'evolve', 'player', 'turn']",do_damage100,attack,player,opponent Pokémon,None
7,Keito Arai,Professor's Research,Trainer,NaN,NaN,NaN,Discard your hand and draw 7 card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,"[('Discard', 'VB'), ('your', 'PRP$'), ('hand', 'NN'), ('and', 'CC'), ('draw', 'VB'), ('7', 'CD'), ('cards', 'NNS'), ('.', '.')]","[('discard', 'VB'), ('your', 'PRP$'), ('hand', 'NN'), ('and', 'CC'), ('draw', 'VB'), ('7', 'CD'), ('card', 'NNS'), ('.', '.')]",NaN,"['pokémon', 'deck', 'card', 'shuffle', 'basic', 'search', 'hand', 'evolve', 'player', 'turn']",discard+draw,hand,player,card(7),None
8,Keito Arai,Iono,Trainer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Keito Arai,Arven,Trainer,NaN,NaN,NaN,Search your deck for an Item card and a Pokémon Tool card reveal them and put them into your hand Then shuffle your deck,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,"[('Search', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('for', 'IN'), ('an', 'DT'), ('Item', 'NN'), ('card', 'NN'), ('and', 'CC'), ('a', 'DT'), ('Pokémon', 'NNP'), ('Tool', 'NN'), ('card', 'NN'), (',', ','), ('reveal', 'VB'), ('them', 'PRP'), (',', ','), ('and', 'CC'), ('put', 'VB'), ('them', 'PRP'), ('into', 'IN'), ('your', 'PRP$'), ('hand', 'NN'), ('.', '.'), ('Then', 'RB'), (',', ','), ('shuffle', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('.', '.')]","[('search', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('for', 'IN'), ('an', 'DT'), ('item', 'NN'), ('card', 'NN'), ('and', 'CC'), ('a', 'DT'), ('pokémon', 'NNP'), ('tool', 'NN'), ('card', 'NN'), (',', ','), ('reveal', 'VB'), ('them', 'PRP'), (',', ','), ('and', 'CC'), ('put', 'VB'), ('them', 'PRP'), ('into', 'IN'), ('your', 'PRP$'), ('hand', 'NN'), ('.', '.'), ('then', 'RB'), (',', ','), ('shuffle', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('.', '.')]",NaN,"['pokémon', 'deck', 'card', 'shuffle', 'basic', 'search', 'hand', 'evolve', 'player', 'turn']",search,deck,player,Item card,shuffle_deck
10,Keito Arai,Ultra Ball,Trainer,NaN,NaN,NaN,Search your deck for a Pokémon reveal it and put it into your hand Then shuffle your deck,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,"[('Search', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('for', 'IN'), ('a', 'DT'), ('Pokémon', 'NNP'), (',', ','), ('reveal', 'VB'), ('it', 'PRP'), (',', ','), ('and', 'CC'), ('put', 'VB'), ('it', 'PRP'), ('into', 'IN'), ('your', 'PRP$'), ('hand', 'NN'), ('.', '.'), ('Then', 'RB'), (',', ','), ('shuffle', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('.', '.')]","[('search', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('for', 'IN'), ('a', 'DT'), ('pokémon', 'NNP'), (',', ','), ('reveal', 'VB'), ('it', 'PRP'), (',', ','), ('and', 'CC'), ('put', 'VB'), ('it', 'PRP'), ('into', 'IN'), ('your', 'PRP$'), ('hand', 'NN'), ('.', '.'), ('then', 'RB'), (',', ','), ('shuffle', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('.', '.')]",NaN,"['pokémon', 'deck', 'card', 'shuffle', 'basic', 'search', 'hand', 'evolve', 'player', 'turn']",search,deck,player,pokémon,shuffle_deck
11,Keito Arai,Earthen Vessel,Trainer,NaN,NaN,NaN,Search your deck for up to 2 Basic Energy card reveal them and put them into your hand Then shuffle your deck,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,"[('Search', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('for', 'IN'), ('up', 'IN'), ('to', 'IN'), ('2', 'CD'), ('Basic', 'JJ'), ('Energy', 'NN'), ('cards', 'NNS'), (',', ','), ('reveal', 'VB'), ('them', 'PRP'), (',', ','), ('and', 'CC'), ('put', 'VB'), ('them', 'PRP'), ('into', 'IN'), ('your', 'PRP$'), ('hand', 'NN'), ('.', '.'), ('Then', 'RB'), (',', ','), ('shuffle', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('.', '.')]","[('search', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('for', 'IN'), ('up', 'IN'), ('to', 'IN'), ('2', 'CD'), ('basic', 'JJ'), ('energy', 'NN'), ('card', 'NNS'), (',', ','), ('reveal', 'VB'), ('them', 'PRP'), (',', ','), ('and', 'CC'), ('put', 'VB'), ('them', 'PRP'), ('into', 'IN'), ('your', 'PRP$'), ('hand', 'NN'), ('.', '.'), ('then', 'RB'), (',', ','), ('shuffle', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('.', '.')]",NaN,"['pokémon', 'deck', 'card', 'shuffle', 'basic', 'search', 'hand', 'evolve', 'player', 'turn']",search,deck,player,Energy card,shuffle_deck
12,Keito Arai,Nest Ball,Trainer,NaN,NaN,NaN,Search your deck for a Basic Pokémon and put it onto your Bench Then shuffle your deck,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,"[('Search', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('for', 'IN'), ('a', 'DT'), ('Basic', 'NNP'), ('Pokémon', 'NNP'), ('and', 'CC'), ('put', 'VB'), ('it', 'PRP'), ('onto', 'IN'), ('your', 'PRP$'), ('Bench', 'NNP'), ('.', '.'), ('Then', 'RB'), (',', ','), ('shuffle', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('.', '.')]","[('search', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('for', 'IN'), ('a', 'DT'), ('basic', 'NNP'), ('pokémon', 'NNP'), ('and', 'CC'), ('put', 'VB'), ('it', 'PRP'), ('onto', 'IN'), ('your', 'PRP$'), ('bench', 'NNP'), ('.', '.'), ('then', 'RB'), (',', ','), ('shuffle', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('.', '.')]",NaN,"['pokémon', 'deck', 'card', 'shuffle', 'basic', 'search', 'hand', 'evolve', 'player', 'turn']",search,deck,player,Basic Pokémon,shuffle_deck
13,Keito Arai,Rare Candy,Trainer,NaN,NaN,NaN,This count a evolve that Pokémon You cant use this card during your first turn or on a Basic Pokémon that be put into play this turn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,"[('(', '-LRB-'), ('This', 'DT'), ('counts', 'VBZ'), ('as', 'IN'), ('evolving', 'VBG'), ('that', 'IN'), ('Pokémon', 'NNP'), ('.', '.'), (')', '-RRB-'), ('You', 'PRP'), ('ca', 'MD'), (""n't"", 'RB'), ('use', 'VB'), ('this', 'DT'), ('card', 'NN'), ('during', 'IN'), ('your', 'PRP$'), ('first', 'JJ'), ('turn', 'NN'), ('or', 'CC'), ('on', 'IN'), ('a', 'DT'), ('Basic', 'JJ'), ('Pokémon', 'NNP'), ('that', 'WDT'), ('was', 'VBD'), ('put', 'VBN'), ('into', 'IN'), ('play', 'NN'), ('this', 'DT'), ('turn', 'NN'), ('.', '.')]","[('(', '-LRB-'), ('this', 'DT'), ('count', 'VBZ'), ('a', 'IN'), ('evolve', 'VBG'), ('that', 'IN'), ('pokémon', 'NNP'), ('.', '.'), (')', '-RRB-'), ('you', 'PRP'), ('ca', 'MD'), (""n't"", 'RB'), ('use', 'VB'), ('this', 'DT'), ('card', 'NN'), ('during', 'IN'), ('your', 'PRP$'), ('first', 'JJ'), ('turn', 'NN'), ('or', 'CC'), ('on', 'IN'), ('a', 'DT'), ('basic', 'JJ'), ('pokémon', 'NNP'), ('that', 'WDT'), ('be', 'VBD'), ('put', 'VBN'), ('into', 'IN'), ('play', 'NN'), ('this', 'DT'), ('turn', 'NN'), ('.', '.')]",NaN,"['pokémon', 'deck', 'card', 'shuffle', 'basic', 'search', 'hand', 'evolve', 'player', 'turn']",count,pokémon,player,you,None
14,Keito Arai,Night Stretcher,Trainer,NaN,NaN,NaN,Put a Pokémon or a Basic Energy card from your discard pile into your hand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,"[('Put', 'VB'), ('a', 'DT'), ('Pokémon', 'NNP'), ('or', 'CC'), ('a', 'DT'), ('Basic', 'JJ'), ('Energy', 'NN'), ('card', 'NN'), ('from', 'IN'), ('your', 'PRP$'), ('discard', 'NN'), ('pile', 'NN'), ('into', 'IN'), ('your', 'PRP$'), ('hand', 'NN'), ('.', '.')]","[('put', 'VB'), ('a', 'DT'), ('pokémon', 'NNP'), ('or', 'CC'), ('a', 'DT'), ('basic', 'JJ'), ('energy', 'NN'), ('card', 'NN'), ('from', 'IN'), ('your', 'PRP$'), ('discard', 'NN'), ('pile', 'NN'), ('into', 'IN'), ('your', 'PRP$'), ('hand', 'NN'), ('.', '.')]",NaN,"['pokémon', 'deck', 'card', 'shuffle', 'basic', 'search', 'hand', 'evolve', 'player', 'turn']",put,pokémon,player,Energy card,None
15,Keito Arai,Super Rod,Trainer,NaN,NaN,NaN,Shuffle up to 3 in any combination of Pokémon and basic Energy card from your discard pile back into your deck,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,"[('Shuffle', 'VB'), ('up', 'IN'), ('to', 'IN'), ('3', 'CD'), ('in', 'IN'), ('any', 'DT'), ('combination', 'NN'), ('of', 'IN'), ('Pokémon', 'NNP'), ('and', 'CC'), ('basic', 'JJ'), ('Energy', 'NN'), ('cards', 'NNS'), ('from', 'IN'), ('your', 'PRP$'), ('discard', 'NN'), ('pile', 'NN'), ('back', 'RB'), ('into', 'IN'), ('your', 'PRP$'), ('deck', 'NN'), ('.', '.')]","[('shuffle', 'VB'), ('up', 'IN'), ('to', 'IN'), ('3', 'CD'), ('in', 'IN'), ('any', 'DT'), ('combination', 'NN'), ('of', 'IN'), ('pokémon', 'NNP'), ('and', 'CC'), ('basic', 'JJ'), ('energy', 'NN'), ('card', 'NNS'), ('from', 'IN'), ('your', 'PRP$'), ('discard', 'NN'), ('pile', 'NN'), ('back', 'RB'), ('into', 'IN'), ('your', 'PRP$'), ('deck', 'NN'), ('.', '.')]",NaN,"['pokémon', 'deck', 'card', 'shuffle', 'basic', 'search', 'hand', 'evolve', 'player', 'turn']",shuffle,combination,player,combination of,None
16,Keito Arai,Counter Catcher,Trainer,NaN,NaN,NaN,Switch in 1 of your opponent Benched Pokémon to the Active Spot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,"[('Switch', 'VB'), ('in', 'IN'), ('1', 'CD'), ('of', 'IN'), ('your', 'PRP$'), ('opponent', 'NN'), (""'s"", 'POS'), ('Benched', 'NNP'), ('Pokémon', 'NNP'), ('to', 'IN'), ('the', 'DT'), ('Active', 'NNP'), ('Spot', 'NNP'), ('.', '.')]","[('switch', 'VB'), ('in', 'IN'), ('1', 'CD'), ('of', 'IN'), ('your', 'PRP$'), ('opponent', 'NN'), (""'s"", 'POS'), ('benched', 'NNP'), ('pokémon', 'NNP'), ('to', 'IN'), ('the', 'DT'), ('active', 'NNP'), ('spot', 'NNP'), ('.', '.')]",NaN,"['pokémon', 'deck', 'card', 'shuffle', 'basic', 'search', 'hand', 'evolve', 'player', 'turn']",switch,opponent,player,benched pokémon-active spot,None
17,Keito Arai,Secret Box,Trainer,NaN,NaN,NaN,Search your deck for an Item card a Pokémon Tool card a Supporter card and a Stadium card reveal them and put them into your hand Then shuffle your deck,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,"[('Search', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('for', 'IN'), ('an', 'DT'), ('Item', 'NN'), ('card', 'NN'), (',', ','), ('a', 'DT'), ('Pokémon', 'NNP'), ('Tool', 'NN'), ('card', 'NN'), (',', ','), ('a', 'DT'), ('Supporter', 'NN'), ('card', 'NN'), (',', ','), ('and', 'CC'), ('a', 'DT'), ('Stadium', 'NN'), ('card', 'NN'), (',', ','), ('reveal', 'VB'), ('them', 'PRP'), (',', ','), ('and', 'CC'), ('put', 'VB'), ('them', 'PRP'), ('into', 'IN'), ('your', 'PRP$'), ('hand', 'NN'), ('.', '.'), ('Then', 'RB'), (',', ','), ('shuffle', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('.', '.')]","[('search', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('for', 'IN'), ('an', 'DT'), ('item', 'NN'), ('card', 'NN'), (',', ','), ('a', 'DT'), ('pokémon', 'NNP'), ('tool', 'NN'), ('card', 'NN'), (',', ','), ('a', 'DT'), ('supporter', 'NN'), ('card', 'NN'), (',', ','), ('and', 'CC'), ('a', 'DT'), ('stadium', 'NN'), ('card', 'NN'), (',', ','), ('reveal', 'VB'), ('them', 'PRP'), (',', ','), ('and', 'CC'), ('put', 'VB'), ('them', 'PRP'), ('into', 'IN'), ('your', 'PRP$'), ('hand', 'NN'), ('.', '.'), ('then', 'RB'), (',', ','), ('shuffle', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('.', '.')]",NaN,"['pokémon', 'deck', 'card', 'shuffle', 'basic', 'search', 'hand', 'evolve', 'player', 'turn']",search,deck,player,Item card,shuffle_deck
18,Keito Arai,Technical Machine: Evolution,Trainer,NaN,NaN,NaN,C Evolution Choose up to 2 of your Benched Pokémon For each of those Pokémon search your deck for a card that evolve from that Pokémon and put it onto that Pokémon to evolve it Then shuffle your deck,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,"[('[', '-LRB-'), ('C', 'NNP'), (']', '-RRB-'), ('EvolutionChoose', 'NN'), ('up', 'IN'), ('to', 'IN'), ('2', 'CD'), ('of', 'IN'), ('your', 'PRP$'), ('Benched', 'NNP'), ('Pokémon', 'NNP'), ('.', '.'), ('For', 'IN'), ('each', 'DT'), ('of', 'IN'), ('those', 'DT'), ('Pokémon', 'NNP'), (',', ','), ('search', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('for', 'IN'), ('a', 'DT'), ('card', 'NN'), ('that', 'WDT'), ('evolves', 'VBZ'), ('from', 'IN'), ('that', 'DT'), ('Pokémon', 'NNP'), ('and', 'CC'), ('put', 'VB'), ('it', 'PRP'), ('onto', 'IN'), ('that', 'DT'), ('Pokémon', 'NNP'), ('to', 'TO'), ('evolve', 'VB'), ('it', 'PRP'), ('.', '.'), ('Then', 'RB'), (',', ','), ('shuffle', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('.', '.')]","[('[', '-LRB-'), ('c', 'NNP'), (']', '-RRB-'), ('evolutionchoose', 'NN'), ('up', 'IN'), ('to', 'IN'), ('2', 'CD'), ('of', 'IN'), ('your', 'PRP$'), ('benched', 'NNP'), ('pokémon', 'NNP'), ('.', '.'), ('for', 'IN'), ('each', 'DT'), ('of', 'IN'), ('those', 'DT'), ('pokémon', 'NNP'), (',', ','), ('search', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('for', 'IN'), ('a', 'DT'), ('card', 'NN'), ('that', 'WDT'), ('evolve', 'VBZ'), ('from', 'IN'), ('that', 'DT'), ('pokémon', 'NNP'), ('and', 'CC'), ('put', 'VB'), ('it', 'PRP'), ('onto', 'IN'), ('that', 'DT'), ('pokémon', 'NNP'), ('to', 'TO'), ('evolve', 'VB'), ('it', 'PRP'), ('.', '.'), ('then', 'RB'), (',', ','), ('shuffle', 'VB'), ('your', 'PRP$'), ('deck', 'NN'), ('.', '.')]",NaN,"['pokémon', 'deck', 'card', 'shuffle', 'basic', 'search', 'hand', 'evolve', 'player', 'turn']",search,c,player,evolutionchoose,None
19,Keito Arai,Bravery Charm,Trainer,NaN,NaN,NaN,The Basic Pokémon this card be attach to get 50 H P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,"[('The', 'DT'), ('Basic', 'NNP'), ('Pokémon', 'NNP'), ('this', 'DT'), ('card', 'NN'), ('is', 'VBZ'), ('attached', 'VBN'), ('to', 'IN'), ('gets', 'VBZ'), ('+50', 'CD'), ('HP', 'NNP'), ('.', '.')]","[('the', 'DT'), ('basic', 'NNP'), ('pokémon', 'NNP'), ('this', 'DT'), ('card', 'NN'), ('be', 'VBZ'), ('attach', 'VBN'), ('to', 'IN'), ('get', 'VBZ'), ('+50', 'CD'), ('hp', 'NNP'), ('.', '.')]",NaN,"['pokémon', 'deck', 'card', 'shuffle', 'basic', 'search', 'hand', 'evolve', 'player', 'turn']",be,basic,player,pokémon,None
20,Keito Arai,Artazon,Trainer,NaN,NaN,NaN,Once during each player turn that player may search their deck for a Basic Pokémon that doesn ’ t have a Rule Box and put it onto their Bench Then that player shuffle their deck Pokémon ex Pokémon V etc have Rule Boxes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,"[('Once', 'IN'), ('during', 'IN'), ('each', 'DT'), ('player', 'NN'), (""'s"", 'POS'), ('turn', 'NN'), (',', ','), ('that', 'DT'), ('player', 'NN'), ('may', 'MD'), ('search', 'VB'), ('their', 'PRP$'), ('deck', 'NN'), ('for', 'IN'), ('a', 'DT'), ('Basic', 'NNP'), ('Pokémon', 'NNP'), ('that', 'WDT'), ('does', 'VBZ'), ('n’t', 'RB'), ('have', 'VB'), ('a', 'DT'), ('Rule', 'NN'), ('Box', 'NN'), ('and', 'CC'), ('put', 'VB'), ('it', 'PRP'), ('onto', 'IN'), ('their', 'PRP$'), ('Bench', 'NNP'), ('.', '.'), ('Then', 'RB'), (',', ','), ('that', 'DT'), ('player', 'NN'), ('shuffles', 'VBZ'), ('their', 'PRP$'), ('deck', 'NN'), ('.', '.'), ('(', '-LRB-'), ('Pokémon', 'NNP'), ('ex', 'NNP'), (',', ','), ('Pokémon', 'NNP'), ('V', 'CD'), (',', ','), ('etc.', 'FW'), ('have', 'VBP'), ('Rule', 'NN'), ('Boxes', 'NNS'), ('.', '.'), (')', '-RRB-')]","[('once', 'IN'), ('during', 'IN'), ('each', 'DT'), ('player', 'NN'), (""'s"", 'POS'), ('turn', 'NN'), (',', ','), ('that', 'DT'), ('player', 'NN'), ('may', 'MD'), ('search', 'VB'), ('their', 'PRP$'), ('deck', 'NN'), ('for', 'IN'), ('a', 'DT'), ('basic', 'NNP'), ('pokémon', 'NNP'), ('that', 'WDT'), ('do', 'VBZ'), ('n’t', 'RB'), ('have', 'VB'), ('a', 'DT'), ('rule', 'NN'), ('box', 'NN'), ('and', 'CC'), ('put', 'VB'), ('it', 'PRP'), ('onto', 'IN'), ('their', 'PRP$'), ('bench', 'NNP'), ('.', '.'), ('then', 'RB'), (',', ','), ('that', 'DT'), ('player', 'NN'), ('shuffle', 'VBZ'), ('their', 'PRP$'), ('deck', 'NN'), ('.', '.'), ('(', '-LRB-'), ('pokémon', 'NNP'), ('ex', 'NNP'), (',', ','), ('pokémon', 'NNP'), ('v', 'CD'), (',', ','), ('etc.', 'FW'), ('have', 'VBP'), ('rule', 'NN'), ('boxes', 'NNS'), ('.', '.'), (')', '-RRB-')]",NaN,"['pokémon', 'deck', 'card', 'shuffle', 'basic', 'search', 'hand', 'evolve', 'player', 'turn']",may search,player,player,turn,None
21,Keito Arai,Psychic Energy,Energy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN